# https://github.com/aspnet/aspnet-docker/issues/401
FROM mcr.microsoft.com/dotnet/core/aspnet:3.0-stretch-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:3.0-stretch AS build
WORKDIR /src
# Copy code files and restore as distinct layers
COPY [".", "."]
RUN dotnet restore "02.csproj"
# build
RUN dotnet build "02.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "02.csproj" -c Release -o /app

# Build runtime image
FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "02.dll"]